// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restoran;

#nullable disable

namespace Restoran.Migrations
{
    [DbContext(typeof(RestoranDbContext))]
    [Migration("20230120131440_RebasedScheme")]
    partial class RebasedScheme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restoran.Customer", b =>
                {
                    b.Property<short>("CId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("CId"));

                    b.Property<string>("CPib")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Restoran.Dish", b =>
                {
                    b.Property<short>("DId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("DId"));

                    b.Property<bool?>("DAviable")
                        .HasColumnType("bit");

                    b.Property<int?>("DCalority")
                        .HasColumnType("int");

                    b.Property<string>("DName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("IngridientIId")
                        .HasColumnType("smallint");

                    b.HasKey("DId");

                    b.HasIndex("IngridientIId");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("Restoran.DishNumerate", b =>
                {
                    b.Property<short>("DnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("DnId"));

                    b.Property<short?>("DishDId")
                        .HasColumnType("smallint");

                    b.Property<int>("DnDishes")
                        .HasColumnType("int");

                    b.Property<decimal?>("DnPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DnTimestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("DnId");

                    b.HasIndex("DishDId");

                    b.ToTable("DishNumerates");
                });

            modelBuilder.Entity("Restoran.Ingridient", b =>
                {
                    b.Property<short>("IId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("IId"));

                    b.Property<bool?>("IAviable")
                        .HasColumnType("bit");

                    b.Property<string>("IName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("IPriceFromZavod")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("IWeight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IId");

                    b.ToTable("Ingridients");
                });

            modelBuilder.Entity("Restoran.Ordering", b =>
                {
                    b.Property<short>("OId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("OId"));

                    b.Property<short?>("DishNumerateDnId")
                        .HasColumnType("smallint");

                    b.Property<short>("OCId")
                        .HasColumnType("smallint");

                    b.Property<short>("ODnId")
                        .HasColumnType("smallint");

                    b.Property<short>("OPId")
                        .HasColumnType("smallint");

                    b.Property<byte>("OPosition")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("OTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<short>("OWId")
                        .HasColumnType("smallint");

                    b.HasKey("OId");

                    b.HasIndex("DishNumerateDnId");

                    b.HasIndex("OCId");

                    b.HasIndex("OPId");

                    b.HasIndex("OWId");

                    b.ToTable("Orderings");
                });

            modelBuilder.Entity("Restoran.Position", b =>
                {
                    b.Property<short>("PId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("PId"));

                    b.Property<short>("PChairs")
                        .HasColumnType("smallint");

                    b.Property<string>("PRoomType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("Restoran.Restoraunt", b =>
                {
                    b.Property<short>("RId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("RId"));

                    b.Property<string>("RAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RClients")
                        .HasColumnType("int");

                    b.Property<string>("RName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("RTables")
                        .HasColumnType("smallint");

                    b.Property<int>("RWorkers")
                        .HasColumnType("int");

                    b.HasKey("RId");

                    b.ToTable("Restorans");
                });

            modelBuilder.Entity("Restoran.Worker", b =>
                {
                    b.Property<short>("CId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("CId"));

                    b.Property<string>("CPib")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WDocument")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WIpn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WRank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WSalary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("Restoran.Dish", b =>
                {
                    b.HasOne("Restoran.Ingridient", null)
                        .WithMany("Recepts")
                        .HasForeignKey("IngridientIId");
                });

            modelBuilder.Entity("Restoran.DishNumerate", b =>
                {
                    b.HasOne("Restoran.Dish", null)
                        .WithMany("Orderings")
                        .HasForeignKey("DishDId");
                });

            modelBuilder.Entity("Restoran.Ordering", b =>
                {
                    b.HasOne("Restoran.DishNumerate", null)
                        .WithMany("Orderings")
                        .HasForeignKey("DishNumerateDnId");

                    b.HasOne("Restoran.Customer", "OC")
                        .WithMany("Orderings")
                        .HasForeignKey("OCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restoran.Position", "OP")
                        .WithMany("Orderings")
                        .HasForeignKey("OPId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restoran.Worker", "OW")
                        .WithMany("Orderings")
                        .HasForeignKey("OWId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OC");

                    b.Navigation("OP");

                    b.Navigation("OW");
                });

            modelBuilder.Entity("Restoran.Customer", b =>
                {
                    b.Navigation("Orderings");
                });

            modelBuilder.Entity("Restoran.Dish", b =>
                {
                    b.Navigation("Orderings");
                });

            modelBuilder.Entity("Restoran.DishNumerate", b =>
                {
                    b.Navigation("Orderings");
                });

            modelBuilder.Entity("Restoran.Ingridient", b =>
                {
                    b.Navigation("Recepts");
                });

            modelBuilder.Entity("Restoran.Position", b =>
                {
                    b.Navigation("Orderings");
                });

            modelBuilder.Entity("Restoran.Worker", b =>
                {
                    b.Navigation("Orderings");
                });
#pragma warning restore 612, 618
        }
    }
}
